# Generated by Django 4.2.15 on 2024-12-28 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=20)),
                ("time_slot", models.CharField(max_length=50)),
                ("mon_7", models.CharField(blank=True, max_length=100, null=True)),
                ("tue_7", models.CharField(blank=True, max_length=100, null=True)),
                ("wed_7", models.CharField(blank=True, max_length=100, null=True)),
                ("thu_7", models.CharField(blank=True, max_length=100, null=True)),
                ("fri_7", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("enrolled", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="ElementaryEnrollment.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=10)),
                ("birth_date", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("street", models.CharField(max_length=100)),
                ("barangay", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("grade_level", models.IntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, max_length=50, null=True)),
                ("first_login", models.BooleanField(default=True)),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("Pending Account Creation", "Pending Account Creation"),
                            ("Pending Enrollment", "Pending Enrollment"),
                            ("Enrolled", "Enrolled"),
                        ],
                        default="Pending Account Creation",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Regular"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_section",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElementaryEnrollment.section",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="ElementaryEnrollment.student",
            ),
        ),
        migrations.CreateModel(
            name="Mother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("contact", models.CharField(max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=50)),
                ("birth_date", models.DateField()),
                ("street", models.CharField(max_length=100)),
                ("barangay", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mother",
                        to="ElementaryEnrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Father",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("contact", models.CharField(max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=50)),
                ("birth_date", models.DateField()),
                ("street", models.CharField(max_length=100)),
                ("barangay", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="father",
                        to="ElementaryEnrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[("new", "New Student"), ("transfer", "Transferee")],
                        max_length=20,
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transfer_reason", models.TextField(blank=True, null=True)),
                ("grade_level", models.CharField(max_length=20)),
                (
                    "kindergarten_certificate",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "transferee_report_card",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElementaryEnrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_uploaded", models.FileField(upload_to="documents/")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ElementaryEnrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_on", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElementaryEnrollment.student",
                    ),
                ),
            ],
        ),
    ]
