# Generated by Django 4.2.15 on 2024-12-28 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ElementaryEnrollment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="section",
            name="enrolled",
        ),
    ]
