# Generated by Django 4.2.15 on 2024-12-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ElementaryEnrollment",
            "0002_remove_section_capacity_remove_section_enrolled",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElementaryEnrollment.section",
            ),
        ),
    ]
