# Generated by Django 4.2.15 on 2024-12-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ElementaryEnrollment", "0003_alter_student_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
